---

- fail: msg="If `backup_authorized_key` is given, `backup_user_shell` must be `true`."
  when: backup_user_shell == false and backup_authorized_key is defined

- fail: msg="`backup_postgresql_enable` is `True`, but `backup_postgresql_database` is not defined."
  when: backup_postgresql_enable and backup_postgresql_database is not defined

- fail: msg="`backup_postgresql_enable` is `True`, but `backup_postgresql_user` is not defined."
  when: backup_postgresql_enable and backup_postgresql_user is not defined

- fail: msg="`backup_postgresql_enable` is `True`, but `vaulted_backup_postgresql_password` is not defined."
  when: backup_postgresql_enable and vaulted_backup_postgresql_password is not defined
