---

- name: Install system dependencies
  package: name={{ item }} state=present
  with_items:
    - python-pip
    - gnupg2
    - ncftp
    - python-paramiko
    - python-boto
    - python-devel
    - librsync-devel
    - python-lockfile
    - mailx
    - gcc

- name: Create download dir
  file: path={{ backup_dist_dir }} state=directory

- name: Download the Duplicity tarball
  get_url:
    url: "{{ backup_duplicity_url }}"
    dest: "{{ backup_dist_dir }}/{{ backup_duplicity_version }}.tar.gz"
  register: backup_download_res

- name: Untar the duplicity tar.gz
  unarchive:
    src: "{{ backup_dist_dir }}/{{ backup_duplicity_version }}.tar.gz"
    dest: "{{ backup_dist_dir }}"
    copy: no

- name: Install duplicity
  shell: >
    python setup.py install
    chdir={{ backup_dist_dir }}/{{ backup_duplicity_version }}
  when: backup_download_res.changed

- name: Install duptools script (Duplicity wrapper)
  template:
    src: bin/duptools.j2
    dest: "{{ backup_bin_dir }}/duptools"
    mode: 0755

- name: Create file with credentials
  template:
    src: home/duplicity_credentials.j2
    dest: "~/.duplicity_credentials"
    mode: 0600
  become_user: "{{ backup_user }}"

- name: Create cron job for backups
  cron:
    name: backup
    special_time: "{{ backup_frequency }}"
    job: "{{ backup_bin_dir }}/duptools backup"
  when: backup_create_cronjob
  become_user: "{{ backup_user }}"
