---

- name: Install system dependencies
  package: name={{ item }} state=present
  with_items:
    - python-pip
    - gnupg2
    - ncftp
    - python-paramiko
    - python-boto
    - python-devel
    - librsync-devel
    - python-lockfile
    - mailx
    - gcc

- name: Create download dir
  file: path={{ ansible_duplicity_dist_dir }} state=directory

- name: Download the Duplicity tarball
  get_url:
    url: "{{ ansible_duplicity_download_url }}"
    dest: "{{ ansible_duplicity_dist_dir }}/{{ ansible_duplicity_version }}.tar.gz"
  register: ansible_duplicity_download_res

- name: Untar the duplicity tar.gz
  unarchive:
    src: "{{ ansible_duplicity_dist_dir }}/{{ ansible_duplicity_version }}.tar.gz"
    dest: "{{ ansible_duplicity_dist_dir }}"
    copy: no

- name: Install duplicity
  shell: >
    python setup.py install
    chdir={{ ansible_duplicity_dist_dir }}/{{ ansible_duplicity_version }}
  when: ansible_duplicity_download_res.changed

- name: Install duptools script (Duplicity wrapper)
  template:
    src: bin/duptools.j2
    dest: "{{ ansible_duplicity_bin_dir }}/duptools"
    mode: 0755

- name: Create file with credentials
  template:
    src: home/duplicity_credentials.j2
    dest: "~/.duplicity_credentials"
    mode: 0700

- name: Create cron job for backups
  cron:
    name: backup
    weekday: "{{ ansible_duplicity_cron_weekday }}"
    day: "{{ ansible_duplicity_cron_day }}"
    hour: "{{ ansible_duplicity_cron_hour }}"
    minute: "{{ ansible_duplicity_cron_minute }}"
    job: "{{ ansible_duplicity_bin_dir }}/duptools backup"
  when: ansible_duplicity_create_cronjob
