---

- include: assertions.yml

- name: Add backup user
  user:
    name: "{{ backup_user }}"
    shell: /bin/bash

- name: Add public SSH key to backup user's authorized_keys file
  authorized_key:
    user: "{{ backup_user }}"
    key: "{{ backup_authorized_key }}"
  when: backup_authorized_key is defined

- include: postgres.yml
  become: yes
  become_user: "{{ backup_user }}"

- include: duplicity.yml
