---

# backup_postgresql_password is defined

- include: system.yml

- include: gpg.yml
  become: yes
  become_user: "{{ backup_user }}"

- include: databases.yml
  become: yes
  become_user: "{{ backup_user }}"

- include: configuration.yml

- include: timer.yml
