---

- name: Prepare directory for storing backups
  file:
    path: "{{ backup_backups_dir }}"
    state: directory
    mode: 0700


- name: Prepare .pgpass file with PostgreSQL access credentials
  template:
    src: pgpass.j2
    dest: ~/.pgpass
    mode: 0600

- name: Install backup script
  template:
    src: backup_databases.py.j2
    dest: ~/backup_databases.py
    mode: 0740

- name: Add backup script to backup user's crontab
  cron:
    name: "Run backup_databases.py"
    special_time: "{{ backup_frequency }}"
    job: "/home/{{ backup_user }}/backup_databases.py"
    state: present
