---

- name: Prepare directory for storing backups
  file:
    path: "{{ backup_backups_dir }}"
    state: directory
    mode: 0700


- name: Prepare .pgpass file with PostgreSQL access credentials
  template:
    src: home/pgpass.j2
    dest: ~/.pgpass
    mode: 0600
  when: backup_postgresql_enable

- name: Install backup script
  template:
    src: bin/backup_databases.py.j2
    dest: "{{ backup_bin_dir }}/backup_databases"
    mode: 0755
  become_user: root

- name: Add backup script to backup user's crontab
  cron:
    name: "Run backup_databases"
    special_time: "{{ backup_frequency }}"
    job: "{{ backup_bin_dir }}/backup_databases"
    state: present
