---

- name: Create backup services
  template:
    src: etc/systemd/system/backup.service.j2
    dest: /etc/systemd/system/backup-{{ item.name }}.service
  with_items: "{{ backup_profiles }}"
  notify: Reload systemd configuration

# - name: Enable backup services
#   systemd:
#     name: "backup-{{ item.name }}.service"
#     enabled: yes
#   with_items: "{{ backup_profiles }}"

- name: Create backup timers
  template:
    src: etc/systemd/system/backup.timer.j2
    dest: /etc/systemd/system/backup-{{ item.name }}.timer
  with_items: "{{ backup_profiles }}"
  notify: Reload systemd configuration

- name: Enable and start backup timers
  systemd:
    name: "backup-{{ item.name }}.timer"
    enabled: yes
    state: started
  with_items: "{{ backup_profiles }}"
