---

- name: Add backup user
  user:
    name: "{{ backup_user }}"
    state: present

- name: Add backup user
  user:
    name: "{{ backup_user }}"
    shell: /sbin/nologin
  when: not backup_user_shell

- name: Add public SSH key to backup user's authorized_keys file
  authorized_key:
    user: "{{ backup_user }}"
    key: "{{ backup_authorized_key }}"
  when: backup_authorized_key is defined
